# Generated by Django 5.1.1 on 2024-10-31 18:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('blog', 'Blog'), ('summary', 'Summary')], default='summary', max_length=10)),
                ('summary', models.TextField()),
            ],
        ),
    ]
