# Generated by Django 5.1.1 on 2024-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
